apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api
  namespace: default
  labels:
    app: products-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-api
  template:
    metadata:
      labels:
        app: products-api
    spec:
      containers:
      - name: products-api
        image: 527055790362.dkr.ecr.ap-south-1.amazonaws.com/products-api:v1
        ports:
        - containerPort: 4000
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
