stages:
  - build
  - deploy

variables:
  REGISTRY: registry.gitlab.com/makingdemoproject
  SERVICE_NAME: web-app
  PORT: "80"

build-push:
  stage: build
  tags:
    - ec2
  script:
    - docker login -u makingdemoproject -p $GITLAB_TOKEN registry.gitlab.com
    - docker build -t $REGISTRY/$SERVICE_NAME:$CI_COMMIT_SHORT_SHA -t $REGISTRY/$SERVICE_NAME:latest .
    - docker push $REGISTRY/$SERVICE_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $REGISTRY/$SERVICE_NAME:latest
  only:
    - main

deploy:
  stage: deploy
  tags:
    - ec2
  script:
    - docker login -u makingdemoproject -p $GITLAB_TOKEN registry.gitlab.com
    - docker pull $REGISTRY/$SERVICE_NAME:$CI_COMMIT_SHORT_SHA
    - docker stop $SERVICE_NAME || true
    - docker rm $SERVICE_NAME || true
    - docker run -d --name $SERVICE_NAME --restart unless-stopped --network microservices-net -p $PORT:$PORT --env-file /home/ec2-user/env/$SERVICE_NAME.env $REGISTRY/$SERVICE_NAME:$CI_COMMIT_SHORT_SHA
  only:
    - main
  needs: [build-push]
